#!/bin/bash
# Railway Model Update Script

echo " Updating Railway OPENAI_MODEL to gpt-4-turbo..."
echo ""
echo "  MANUEL ADIMLAR:"
echo "1. Git: https://railway.app/project/hsercanalysisagenticai"
echo "2. Variables tab'ı aç"
echo "3. OPENAI_MODEL değişkenini bul"
echo "4. Değeri değiştir: gpt-4-turbo"
echo "5. Save tıkla"
echo ""
echo " Railway otomatik redeploy edecek (1-2 dakika)"
echo ""
echo " Model Karşılaştırma:"
echo "- gpt-4o-mini: $0.005/incident (hızlı, basit)"
echo "- gpt-4-turbo: $0.08/incident (yavaş, derin analiz)"
echo ""
echo "🎯 Beklenen İyileştirmeler:"
echo "- 4-5 immediate causes (önce 2)"
echo "- 5-6 underlying causes (önce 2-3)"
echo "- 5 detaylı root causes (önce 1-2)"
echo "- HSG245 standardına tam uygunluk"
echo "- UK regulations referansları"
echo ""
